/** ブルーバック動画から抽出・背景透過した成体オオサンショウウオの遊泳フレーム。 */
export const ADULT_WALK_FRAMES = [
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_01.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_02.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_03.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_04.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_05.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_06.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_07.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_08.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_09.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_10.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_11.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_12.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_13.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_14.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_15.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_16.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_17.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_18.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_19.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_20.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_21.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_22.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_23.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_24.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_25.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_26.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_27.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_28.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_29.png'),
  require('../assets/images/oosan_adult_swim_blue_30/oosan_adult_swim_blue_30.png'),
] as const;
